### ISSUE TITLE
Add fail on promise error

### ISSUE THREAD

**Issue by mxfo** [yupiik/yupiik-batch#7]
There is no distinction between completed and completed exceptionally promise step. 
Can we add configuration to manage this 2 stages?

**Comment by rmannibucau** [comment]
Note: the actual issue is that dropping the promise when a step is done makes the await logic not behaving properly. In case of a failure it means the fail fast implementation will not await all promise. A good enough fix is to not drop the failed promises to force them to be awaited. Successful promises can be dropped when done to save a bit of memory since it will not impact await logic (allOf). Flag is the way to go to not break anyone IMHO.
